com.capturebliss.api.s3.root-qualifier=root
com.capturebliss.api.q.region=us-east-2
com.capturebliss.api.s3.cdn=scdna.capturebliss.com
com.capturebliss.app.dns=https://app.capturebliss.com
com.capturebliss.api.self.public-endpoint=https://api.service.capturebliss.com
#sentry
sentry.dsn=${SENTRY_DSN}
sentry.traces-sample-rate=1.0
sentry.exception-resolver-order=-2147483647
sentry.environment=${APP_ENV}
sentry.send-default-pii=true
sentry.max-request-body-size=ALWAYS
sentry.release=@pom.version@
auth0.audiences=https://api.service.capturebliss.com
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://capturebliss.us.auth0.com/
com.capturebliss.payment.ai-charge-id=ai-credit-USD
