com.capturebliss.api.s3.root-qualifier=root
com.capturebliss.api.q.region=eu-central-1
com.capturebliss.api.s3.cdn=scdna.capturebliss.com
com.capturebliss.app.dns=https://capturebliss.fambliss.eu
com.capturebliss.api.self.public-endpoint=https://api.capturebliss.fambliss.eu
#sentry
sentry.dsn=${SENTRY_DSN}
sentry.traces-sample-rate=1.0
sentry.exception-resolver-order=-2147483647
sentry.environment=${APP_ENV}
sentry.send-default-pii=true
sentry.max-request-body-size=ALWAYS
sentry.release=@pom.version@
auth0.audiences=backend
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-vsfoa2y1lhzvmfic.us.auth0.com/
com.capturebliss.payment.ai-charge-id=ai-credit-USD
